//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aariaz_Workshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public string Description { get; set; }
        public int Image { get; set; }
        public int Quantity { get; set; }
        public string CostPrice { get; set; }
        public string RetailPrice { get; set; }
        public int SizeSmail { get; set; }
        public int SizeMedium { get; set; }
        public int SizeLarge { get; set; }
        public int SizeXl { get; set; }
        public int Size22 { get; set; }
        public int Size24 { get; set; }
        public int Size26 { get; set; }
        public int Size28 { get; set; }
        public int Size30 { get; set; }
        public int Size32 { get; set; }
        public int Size34 { get; set; }
        public int Size36 { get; set; }
        public bool Status { get; set; }
        public int SalesPercentage_id { get; set; }
        public int User_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual salespercentage salespercentage { get; set; }
    }
}
