//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aariaz_Workshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockdiscrepancy
    {
        public int Id { get; set; }
        public int Shop_id { get; set; }
        public int Product_id { get; set; }
        public int User_id { get; set; }
        public int Status { get; set; }
    }
}
