//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aariaz_Workshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int Id { get; set; }
        public string EmployeeCode { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public string NIC { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public int JobDesignation { get; set; }
        public string Salary { get; set; }
        public int User_id { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
    }
}
