//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aariaz_Workshop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aaraiz_dbEntities : DbContext
    {
        public aaraiz_dbEntities()
            : base("name=aaraiz_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<barcodehistory> barcodehistories { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<leave> leaves { get; set; }
        public virtual DbSet<operatingsite> operatingsites { get; set; }
        public virtual DbSet<paymentorreceived> paymentorreceiveds { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<receipt> receipts { get; set; }
        public virtual DbSet<sale> sales { get; set; }
        public virtual DbSet<salespercentage> salespercentages { get; set; }
        public virtual DbSet<shop> shops { get; set; }
        public virtual DbSet<shopuser> shopusers { get; set; }
        public virtual DbSet<stockdata> stockdatas { get; set; }
        public virtual DbSet<stockdiscrepancy> stockdiscrepancies { get; set; }
        public virtual DbSet<supplier_customer> supplier_customer { get; set; }
        public virtual DbSet<tradingcompany> tradingcompanies { get; set; }
        public virtual DbSet<transferstock> transferstocks { get; set; }
        public virtual DbSet<warehouse> warehouses { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
